### ISSUE TITLE
笔记001

### ISSUE THREAD

**Issue by twocucao** [herryzhang/algorithm-python#2]
基础概念

数据结构为算法服务，算法要作用在特定的数据结构之上。
数据结构：
* 数组
* 连标
* 栈
* 队列
* 堆
* 跳表
* 图
* Trie 树
算法：
* 递归
* 排序
* 二分查找
* 搜索
* 哈希算法
* 贪心算法
* 分治算法
* 回溯算法
* 动态规划
* 字符串匹配算法
算法和数据结构的目的在于：
* 快：运行更快 - 可以类比为效率
* 省：节省存储空间 - 可以类比为省钱
复杂度分析是用于判断一个东西是不是有效率，是不是省钱，往往可以通过如下的途径：
1. 写代码之前估算 - 事前分析估算法
2. 写代码之后运行总结 - 事后统计法
在日常开发中都是选用事后统计法，先写出来，运行，然后优化，而事后统计法的弊病在于
1. 万一这坨代码写出来太耗费时间了，写出来结果是糟糕的，岂不是用战术上的勤奋来掩盖战略上的偷懒的么？
2. 并不一定能在运行过程中完整还原环境要的基本要素。比如测试环境和生产环境不一致，配置不一致。mock 的数据规模不一致。
事前分析估算法
如何估计？
* 算法时间复杂度
推导大 O 阶：
1. 用常数 1 取代运行时间中的所有加法常数。
2. 在修改后的运行次数函数中，只保留最高阶项。
3. 如果最高阶项存在且不是 1, 则去除与这个项相乘的常数。
得到的结果就是大 O 阶。
* 常数阶
* 对数阶
* 线性阶
* nlogn 阶
* 平方阶
* 立方阶
* 指数阶
最坏情况与平均情况

**Comment by twocucao** [comment]
@herryzhang  我们可以把笔记都放在这里

**Comment by herryzhang** [comment]
OK

**Comment by herryzhang** [comment]
霸气，上班时间也可以搞吗？
